Code/dotnetLexChatBot/Models/ChatBotMessage.cs
/*******************************************************************************
* Copyright 2009-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
* 
* Licensed under the Apache License, Version 2.0 (the "License"). You may
* not use this file except in compliance with the License. A copy of the
* License is located at
* 
* http://aws.amazon.com/apache2.0/
* 
* or in the "license" file accompanying this file. This file is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied. See the License for the specific
* language governing permissions and limitations under the License.
*******************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotnetLexChatBot.Models
{
    public class ChatBotMessage
    {

        //0 -> UserMessage 
        //1-> BotMessage
        public int ID { get; set; }
        public MessageType MsgType { get; set; }
        public string ChatMessage { get; set; }
    }

    public enum MessageType
    {
        UserMessage,
        LexMessage
    }
}

Code/dotnetLexChatBot/Controllers/HelloChatBotController.cs
/*******************************************************************************
* Copyright 2009-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
* 
* Licensed under the Apache License, Version 2.0 (the "License"). You may
* not use this file except in compliance with the License. A copy of the
* License is located at
* 
* http://aws.amazon.com/apache2.0/
* 
* or in the "license" file accompanying this file. This file is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied. See the License for the specific
* language governing permissions and limitations under the License.
*******************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Text.Encodings.Web;
using dotnetLexChatBot.Models;
using dotnetLexChatBot.Data;
using System.Net.Http;
using System.Xml;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace dotnetLexChatBot.Controllers
{
    public class HelloChatBotController : Controller
    {
        //Collection of ChatBot Messages

        //static Dictionary<string, string> lexSessionData = new Dictionary<string, string>();
        private readonly IAWSLexService awsLexSvc;
        private ISession userHttpSession;
        private Dictionary<string, string> lexSessionData;
        private List<ChatBotMessage> botMessages;
        private string botMsgKey = "ChatBotMessages", 
                       botAtrribsKey = "LexSessionData",
                       userSessionID = String.Empty;


        public HelloChatBotController(IAWSLexService awsLexService)
        {
            awsLexSvc = awsLexService;
        }

        public IActionResult TestChat(List<ChatBotMessage> messages)
        {
            return View(messages);
        }

        public IActionResult ClearBot()
        {
            userHttpSession = HttpContext.Session;
            
            //Clear session keys and session information without removing Session ID
            userHttpSession.Clear();

            //New botMessages and lexSessionData objects
            botMessages = new List<ChatBotMessage>();
            lexSessionData = new Dictionary<string, string>();

            userHttpSession.Set<List<ChatBotMessage>>(botMsgKey, botMessages);
            userHttpSession.Set<Dictionary<string, string>>(botAtrribsKey, lexSessionData);
            
            awsLexSvc.Dispose();
            return View("TestChat", botMessages);
        }

        [HttpGet]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetChatMessage(string userMessage)
        {
            //Get user session and chat info
            userHttpSession = HttpContext.Session;
            userSessionID = userHttpSession.Id;
            botMessages = userHttpSession.Get<List<ChatBotMessage>>(botMsgKey) ?? new List<ChatBotMessage>();
            lexSessionData = userHttpSession.Get<Dictionary<string, string>>(botAtrribsKey) ?? new Dictionary<string, string>();

            //No message was provided, return to current view
            if (String.IsNullOrEmpty(userMessage)) return View("TestChat", botMessages);

            //A Valid Message exists, Add to page and allow Lex to process
            botMessages.Add(new ChatBotMessage()
            { MsgType = MessageType.UserMessage, ChatMessage = userMessage });

            await postUserData(botMessages);

            //Call Amazon Lex with Text, capture response
            var lexResponse = await awsLexSvc.SendTextMsgToLex(userMessage, lexSessionData, userSessionID);

            lexSessionData = lexResponse.SessionAttributes;
            botMessages.Add(new ChatBotMessage()
            { MsgType = MessageType.LexMessage, ChatMessage = lexResponse.Message });

            //Add updated botMessages and lexSessionData object to Session
            userHttpSession.Set<List<ChatBotMessage>>(botMsgKey, botMessages);
            userHttpSession.Set<Dictionary<string, string>>(botAtrribsKey, lexSessionData);
           
            return View("TestChat", botMessages);
        }

        public async Task<IActionResult> postUserData(List<ChatBotMessage> messages)
        {
            //testing
            return await Task.Run(() => TestChat(messages));
        }

        
    }

}

Code/dotnetLexChatBot/Views/HelloChatBot/Index.cshtml
@*
  Comments  
*@
@model IEnumerable<dotnetLexChatBot.Models.ChatBotMessage>
@{
    ViewData["Title"] = ".NET Lex ChatBot";
}

<html>

<head>
    <title>.NET Amazon Lex ChatBot - Sample Application (BookTrip)</title>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.41.0.min.js"></script>
    <style language="text/css">
        input#wisdom {
            padding: 4px;
            font-size: 1em;
            width: 400px
        }

        input::placeholder {
            color: #ccc;
            font-style: italic;
        }

        ::-webkit-input-placeholder { /* WebKit, Blink, Edge */
            color: #ccc;
            font-style: italic;
        }

        :-moz-placeholder { /* Mozilla Firefox 4 to 18 */
            color: #ccc;
            font-style: italic;
        }

        ::-moz-placeholder { /* Mozilla Firefox 19+ */
            color: #909;
            opacity: 1;
        }

        :-ms-input-placeholder { /* Internet Explorer 10-11 */
            color: #ccc;
            font-style: italic;
        }

        ::-ms-input-placeholder { /* Microsoft Edge */
            color: #ccc;
            font-style: italic;
        }

        dt.userRequest {
            margin: 4px;
            padding: 4px 10px 4px 10px;
            border-radius: 4px;
            min-width: 50%;
            max-width: 85%;
            float: left;
            background-color: #7d7;
        }

        dd.lexResponse {
            margin: 4px;
            padding: 4px 10px 4px 10px;
            border-radius: 4px;
            text-align: right;
            min-width: 50%;
            max-width: 85%;
            float: right;
            background-color: #bbf;
            font-style: italic;
        }

        p.lexError {
            margin: 4px;
            padding: 4px 10px 4px 10px;
            border-radius: 4px;
            text-align: right;
            min-width: 50%;
            max-width: 85%;
            float: right;
            background-color: #f77;
        }
    </style>
</head>

<body>
    <h1>A .NET ChatBot Using Lex</h1>

    <p>Hello from the View Template</p>
    <h2 style="text-align:  left">Amazon Lex - BookTrip</h2>
    <p style="width: 400px">
        This little chatbot shows how easy it is to incorporate
        <a href="https://aws.amazon.com/lex/" title="Amazon Lex (product)" target="_new">Amazon Lex</a> into your web pages.  Try it out.
    </p>
    <div id="conversation" style="width: 400px; height: 400px; border: 1px solid #ccc; background-color: #eee; padding: 4px; overflow: scroll">
        <dl>
            @foreach (var ChatMsg in Model)
            {
                if (ChatMsg.MsgType == dotnetLexChatBot.Models.MessageType.UserMessage)
                {
                    <dt class="userRequest">@ChatMsg.ChatMessage</dt>
                }
                else
                {
                    <dd class="lexResponse">@ChatMsg.ChatMessage</dd>
                }
            }  
            
        </dl>
    </div>
    @using (Html.BeginForm("GetChatMessage","HelloChatBot"))
    {
        <input type="text" size="80" name="userMessage" placeholder="I need a hotel room"/>
    }
    <!--
    <form id="chatform" style="margin-top: 10px" onsubmit="return pushChat();">
        <input type="text" id="wisdom" size="80" value="" placeholder="I need a hotel room">
    </form>-->
</body>
</html>

Code/dotnetLexChatBot/Views/HelloChatBot/TestChat.cshtml
<!DOCTYPE html>
@*
    Comments
*@
@model IEnumerable<dotnetLexChatBot.Models.ChatBotMessage>
@{
    Layout = null;
    ViewData["Title"] = ".NET Lex ChatBot";
}

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>.NET Amazon Lex ChatBot - Sample Application (OrderFlowers)</title>
        <script src="https://sdk.amazonaws.com/js/aws-sdk-2.41.0.min.js"></script>
        <script src="~/js/chatbot/jquery-1.10.2.js" type="text/javascript"></script>
        <script src="~/js/chatbot/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
        <script ssrc="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="~/js/chatbot/awesome-landing-page.js" type="text/javascript"></script>
        <style language="text/css">
            input#wisdom {
                padding: 4px;
                font-size: 1em;
                width: 400px
            }

            input::placeholder {
                color: #ccc;
                font-style: italic;
            }

            ::-webkit-input-placeholder { /* WebKit, Blink, Edge */
                color: #ccc;
                font-style: italic;
            }

            :-moz-placeholder { /* Mozilla Firefox 4 to 18 */
                color: #ccc;
                font-style: italic;
            }

            ::-moz-placeholder { /* Mozilla Firefox 19+ */
                color: #909;
                opacity: 1;
            }

            :-ms-input-placeholder { /* Internet Explorer 10-11 */
                color: #ccc;
                font-style: italic;
            }

            ::-ms-input-placeholder { /* Microsoft Edge */
                color: #ccc;
                font-style: italic;
            }

            dt.userRequest {
                margin: 4px;
                padding: 4px 10px 4px 10px;
                border-radius: 4px;
                min-width: 50%;
                max-width: 85%;
                float: left;
                background-color: #7d7;
            }

            dd.lexResponse {
                margin: 4px;
                padding: 4px 10px 4px 10px;
                border-radius: 4px;
                text-align: right;
                min-width: 50%;
                max-width: 85%;
                float: right;
                background-color: #bbf;
                font-style: italic;
            }

            td.button-cell {
                margin: 4px;
                padding: 4px 10px 4px 10px;
            }

            p.lexError {
                margin: 4px;
                padding: 4px 10px 4px 10px;
                border-radius: 4px;
                text-align: right;
                min-width: 50%;
                max-width: 85%;
                float: right;
                background-color: #f77;
            }
        </style>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/chatbot/landing-page.css" rel="stylesheet" />
        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css' />
        <link href="~/css/chatbot/pe-icon-7-stroke.css" rel="stylesheet" />
    </head>
    <body class="landing-page landing-page1">
        <div class="wrapper">
            <div class="parallax filter-gradient blue" data-color="blue">
                <div class="parallax-background">
                    <img class="parallax-background-image" src="~/images/bg3.jpg">
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="parallax-image">
                                <div id="chatheader" style="width: 400px;height: 60px;border: 1px solid gray;background-color: cadetblue;border-radius: 10px">
                                    <img src="~/images/awspowered-sm.png" style="float:left; margin-top:2px;max-height:95%; max-width:20%;border: 1px solid #7b7b7b;border-radius: 50%;"/>
                                    <h4 style="margin-top:15px;float:left;padding-left:5px;color:white">Order Flowers</h4>
                                </div>
                                <div id="conversation" style="width: 400px; height: 450px; border: 2px solid gray;background-color: #ffffff; overflow: scroll;object-position:bottom">
                                    <dl>
                                        @foreach (var ChatMsg in Model)
                                        {
                                            if (ChatMsg.MsgType == dotnetLexChatBot.Models.MessageType.UserMessage)
                                            {
                                            <dt class="userRequest">@ChatMsg.ChatMessage</dt>
                                            }
                                            else
                                            {
                                            <dd class="lexResponse">@ChatMsg.ChatMessage</dd>
                                            }
                                        }
                                    </dl>
                                </div>
                                @{
                                    <script>
                                        var chatDiv = document.getElementById("conversation");
                                        chatDiv.scrollTop = chatDiv.scrollHeight;
                                    </script>

                                    var htmlAttributes = new Dictionary<string, object>();
                                    htmlAttributes.Add("class", "form-inline");
                                }

                                @using (Html.BeginForm("GetChatMessage","HelloChatBot",FormMethod.Post, htmlAttributes))
                                {
                                    <div class="form-group">
                                        <input class="form-control" name="userMessage" type="text" placeholder="Enter your chat here" style="float:left;width:400px;z-index:-1;background-color: #ffffff;height:39px"/>
                                        <a asp-action="ClearBot" class="btn btn-default" role="button" style="background-color:cadetblue;float:right;margin-top:-39px;color:white">Clear</a>
                                    </div>
                                }
                            </div>
                            
                        </div>
                        
                        <div class="col-md-6 col-md-offset-1">
                            <div class="description" style="margin-top:100px">
                                <h2>.NET ChatBot with Amazon Lex</h2>
                                <br>
                                <h5>Build a .NET Chatbot using ASP .NET Core and Amazon Lex! This chatbot allows you to order flowers. To start using this bot simply type “I want to order flowers”, “Order Flowers” or a similar utterance. This simple chatbot currently is designed to follow three instructions,  type of flowers, day for pick up  and time for     pick up. You can input three types of flowers: Roses, Lilies, and Tulips. Time must be noted with PM/AM and dates can be noted with day i.e. Wednesday or Next Wednesday.. We challenge you to take this simple example, add more details and customize it for your use case</h5>
                            </div>
                            <div class="buttons" style="margin-top:20px">
                                <table>
                                    <tr>
                                        <td class="button-cell">
                                            <form action="http://aws.amazon.com/lex">
                                                <button type="submit" class="btn btn-fill btn-neutral">
                                                    Amazon Lex
                                                </button>
                                            </form>
                                        </td>
                                        <td class="button-cell">
                                            <form action="http://aws.amazon.com/sdk-for-net">
                                                <button type="submit" class="btn btn-fill btn-neutral">
                                                    AWS SDK for .NET
                                                </button>
                                            </form>
                                        </td>
                                        <td class="button-cell">
                                            <form action="http://aws.amazon.com/lambda">
                                                <button class="btn btn-fill btn-neutral">
                                                    AWS Lambda
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

Code/dotnetLexChatBot/Views/HelloChatBot/View.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
</body>
</html>

Code/dotnetLexChatBot/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AWS ChatBot</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">dotnetLexChatBot</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - dotnetLexChatBot</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>